# Generated by Django 4.2.7 on 2024-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_alter_applicability_good'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering'], 'verbose_name': 'Раздел каталога (Код ОКДП2)', 'verbose_name_plural': 'Разделы каталога (Классификатор кодов ОКДП2)'},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Параметр сортировки'),
        ),
    ]
