# Generated by Django 4.2.7 on 2024-04-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_alter_category_options_category_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Параметр сортировки'),
        ),
    ]
