# Generated by Django 4.2.7 on 2024-06-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_alter_category_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='price',
        ),
    ]
