# Generated by Django 4.2.7 on 2024-06-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_remove_good_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена'),
        ),
    ]
