# Generated by Django 4.2.7 on 2024-01-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование'),
        ),
    ]
