# Generated by Django 3.2.23 on 2024-01-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='Файл изображения'),
        ),
    ]
