# Generated by Django 3.2.23 on 2024-03-05 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, default='б/н', max_length=25, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата'),
        ),
    ]
