# Generated by Django 4.2.7 on 2024-03-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20240305_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PD', 'Подготовлен'), ('PK', 'Собирается'), ('SH', 'Отгружен')], default='PD', max_length=2, null=True, verbose_name='Статус'),
        ),
    ]
