# Generated by Django 4.2.7 on 2024-03-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_orderstatus_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='value',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Значение'),
        ),
    ]
