# Generated by Django 4.2.7 on 2024-04-08 05:41

from django.db import migrations, models
import django.db.models.deletion
import order_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_alter_orderstatus_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=order_app.models.OrderStatus.default_order_status, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_app.orderstatus', verbose_name='Статус'),
        ),
    ]
