# Generated by Django 3.2.23 on 2023-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$RPakvZK1TKtaji6wKWfiBS$eRlvBsYSEVLmrce0qdC6mdTqur5FxMFw1CHDFOBrlY4=', max_length=128, verbose_name='password'),
        ),
    ]
