# Generated by Django 4.2.7 on 2023-12-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$oD7Kr2KoZAtMbXnMgyPqHX$767Xc1Zq/QDCJCwq1pBAZFu67ICsKiFURfttkm4mjdk=', max_length=128, verbose_name='password'),
        ),
    ]
