# Generated by Django 4.2.7 on 2023-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ovpjwWDd6prEDnWcK8v84C$ActGHtLi+sQYOrXgfU+djCx6ZIR/rmS3kuyZBCG+j78=', max_length=128, verbose_name='password'),
        ),
    ]
