# Generated by Django 4.2.7 on 2024-01-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$VW2NlqPSDEZThnh3ysWZJ3$WueoclVGYPwygOxu/cbviegDsy/KXAQKTH1NhP7hHQE=', max_length=128, verbose_name='password'),
        ),
    ]
