# Generated by Django 3.2.23 on 2024-01-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$ZH0mTLG21bhptLXcM8ad9i$H1kDC2lzgdDrblgC0hWFE47YBwY2QKKHYpmrQna/Dao=', max_length=128, verbose_name='password'),
        ),
    ]
