# Generated by Django 3.2.23 on 2024-01-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$wPIEb7qsM9UzTaEI972Vds$jJ9V04xDaepmndxjpMY9f7D/5C36Gsv10pTGJnmsB1M=', max_length=128, verbose_name='password'),
        ),
    ]
