# Generated by Django 3.2.23 on 2024-01-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$FqhEBnee0Mna6f5FVMWfpQ$iDQV5JpiLoIT5jGv0usJUTUbInEOVb6A/TQg9jWsMPs=', max_length=128, verbose_name='password'),
        ),
    ]
