# Generated by Django 4.2.7 on 2024-02-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$mIRATjx23sggwd7KWQlZy5$/hTJlmG1e95Ht3fthZzfnX4O6U82VR5mS0Pd6qHQsi0=', max_length=128, verbose_name='password'),
        ),
    ]
