# Generated by Django 4.2.7 on 2024-02-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$p67aMxUC1Bhe5n2KIU264W$aU+ZVGfsr/7G7U8fRUkylaO3u1hvdgsIqjRQ6MBsh/E=', max_length=128, verbose_name='password'),
        ),
    ]
