# Generated by Django 4.2.7 on 2024-02-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$a36P0qvINwkvpG7NC5lKCs$4+N5tC5hSoOD4fD77Xl8eQ7MzXND38VgHoztqUQi4l8=', max_length=128, verbose_name='password'),
        ),
    ]
