# Generated by Django 4.2.7 on 2024-02-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$bvzADWlQhxA5YL397AZISE$zW7V1eZdWQONtlSCO8j6eK7enprAut1qqtnyV2Fpu4c=', max_length=128, verbose_name='password'),
        ),
    ]
