# Generated by Django 3.2.23 on 2024-02-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_user_password'),
        ('auth_app', '0013_alter_user_password'),
    ]

    operations = [
    ]
