# Generated by Django 3.2.23 on 2024-03-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_merge_20240229_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$7K7CnL1gqMty2MCKciBeWx$+eEccQ85VPbcPdGwWwD1YtaebAzC5AyTxYW+DmBZqQQ=', max_length=128, verbose_name='password'),
        ),
    ]
