# Generated by Django 4.2.7 on 2024-03-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zekIc7z6pPiz6MWWvvxnsF$sCH/YhQ3abPedjHlkq2jyRCV/4ELJs5Bi4p8RQpicw4=', max_length=128, verbose_name='password'),
        ),
    ]
