# Generated by Django 4.2.7 on 2024-03-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$beUDAVyK0wUYhncXjbHzVb$7VhWTL9Ud3XXwpnYB94FLrpmvvVkkwM3wxHzDpn2t4A=', max_length=128, verbose_name='password'),
        ),
    ]
