# Generated by Django 4.2.7 on 2024-03-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$svdFn1lxdLZVhOS9PeQABb$H9UI73j0w1RlWlCEwFi0/C4UmEbvyK6ci22eRRKPUH4=', max_length=128, verbose_name='password'),
        ),
    ]
