# Generated by Django 4.2.7 on 2024-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$hkZLIFbrHRerkGCsw6knLk$U6szDkuRiXqHbPYgfjPHOBb5OOWAy3iO0dAvzgoY3kQ=', max_length=128, verbose_name='password'),
        ),
    ]
