# Generated by Django 4.2.7 on 2024-04-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$b7q81FVcWdsA7iEsS59A4J$c9PmgBzRl07/LT3aBd92EAZoGRrqAvUbMhQ7MYwdW0k=', max_length=128, verbose_name='password'),
        ),
    ]
