# Generated by Django 4.2.7 on 2024-04-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Od834KOP4vCRy4c2RsfIXL$UXNbVxlds5HcbFnm04qYWj4hkcZp15cSj2a4HXJnG0A=', max_length=128, verbose_name='password'),
        ),
    ]
