# Generated by Django 4.2.7 on 2024-04-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$RpSUgRz4JLnWpBerKrjpWr$zOE+33F5pijgADK0bwELenQ5RM3s5Ki83B/dMOCanao=', max_length=128, verbose_name='password'),
        ),
    ]
