# Generated by Django 4.2.7 on 2024-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zuab0ajFSxBVQmlqCv7O7z$gdFw3JyZOJFq6//f9xqQs6huCVp7LelPhF0BSZT9JVQ=', max_length=128, verbose_name='password'),
        ),
    ]
