# Generated by Django 4.2.7 on 2024-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Z3yRPAh16vFfdHwx8mlrG5$kWrJSXkWXotNeen/1LBowKBEPqiKcP3ArzhFKAVb14c=', max_length=128, verbose_name='password'),
        ),
    ]
