# Generated by Django 4.2.7 on 2024-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$U4cO4gS6DPJBfvIG0WshrZ$O8BfKrFaCPv6UIafLnXJZO53e0kFWBH1HCkd4HL3zz0=', max_length=128, verbose_name='password'),
        ),
    ]
