# Generated by Django 4.2.7 on 2024-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$KmOWAaPxjUfnbUeMVOSMGo$CwIaGRmJySunTlAVUyd6XPoyozkzZIh1SFav6uec12I=', max_length=128, verbose_name='password'),
        ),
    ]
