# Generated by Django 4.2.7 on 2024-06-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0033_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$7VN52skOxhmxBOrBjxc3ID$5ay4/JunM6YpohRriMTaVCXCnO961HHA6xPPSTqp9NA=', max_length=128, verbose_name='password'),
        ),
    ]
