# Generated by Django 3.2.23 on 2024-06-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$fLNInYWbpf1cdD6Yc4bzY5$rzfuAhmgdAEPBtU8WO6GOqI4Bii6ffSFO1GsRk5ssJc=', max_length=128, verbose_name='password'),
        ),
    ]
