# Generated by Django 3.2.23 on 2024-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$y28HZH9m9E0nLhx1Vg8IUI$Os3swIkSWkbD/Q3yZo7eYp1UaF6Lfonf648iecuHwxo=', max_length=128, verbose_name='password'),
        ),
    ]
