# Generated by Django 4.2.7 on 2024-06-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$MnsqlvmO4ShkZ6eJXZOOKl$vC5OS9u5LLMWl6rffN9QX2/lZ19Qx86OvSx9lZVq2lI=', max_length=128, verbose_name='password'),
        ),
    ]
