# Generated by Django 4.2.7 on 2024-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sXIuSW4zRi9K5aQzywc6PY$g8JW0RM+f9+FujAmYuYyIYVIxfIb1smEZbYB2oyzqws=', max_length=128, verbose_name='password'),
        ),
    ]
