# Generated by Django 4.2.7 on 2024-06-06 08:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_app', '0005_alter_category_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид цены',
                'verbose_name_plural': 'Виды цен',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog_app.good', verbose_name='Товар')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='price_app.kindprice', verbose_name='Вид цены')),
            ],
            options={
                'verbose_name': 'Запись регистрации цен',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
