# Generated by Django 4.2.7 on 2024-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['kind', 'good'], name='price_app_p_kind_id_4f6bff_idx'),
        ),
    ]
