# Generated by Django 4.2.7 on 2024-06-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_alter_category_ordering'),
        ('price_app', '0002_price_price_app_p_kind_id_4f6bff_idx'),
    ]

    operations = [
        #migrations.RemoveIndex(
        #    model_name='price',
        #    name='price_app_p_kind_id_4f6bff_idx',
        #),
        migrations.AlterIndexTogether(
            name='price',
            index_together={('kind', 'good')},
        ),
    ]
