# Generated by Django 4.2.7 on 2024-06-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_remove_good_price'),
        ('price_app', '0003_remove_price_price_app_p_kind_id_4f6bff_idx_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='price',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('kind', 'good')},
        ),
    ]
