# Generated by Django 4.2.7 on 2024-02-29 05:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_app', '0004_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Описание')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='image_app.image', verbose_name='Изображение (превью)')),
            ],
            options={
                'verbose_name': 'Рекламное объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='ValuePropertyOfAnAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('value', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Значение')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advertisement_app.advertisement', verbose_name='Рекламное объявление')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advertisement_app.property', verbose_name='Свойство')),
            ],
            options={
                'verbose_name': 'Значение свойства объявления',
                'verbose_name_plural': 'Значения свойств объявлений',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementsImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='advertisement_app.advertisement', verbose_name='Рекламное объявление')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_app.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения объявления',
            },
        ),
    ]
