# Generated by Django 4.2.7 on 2024-02-29 05:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа свойств',
                'verbose_name_plural': 'Группы свойств',
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства объявлений'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='property',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='advertisement_app.groupofproperty', verbose_name='Группа свойства'),
        ),
    ]
