# Generated by Django 4.2.7 on 2024-04-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_app', '0004_groupofproperty_ordering_property_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupofproperty',
            options={'ordering': ['ordering'], 'verbose_name': 'Группа свойств', 'verbose_name_plural': 'Группы свойств объевлений'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['ordering'], 'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства объявлений'},
        ),
        migrations.AlterField(
            model_name='groupofproperty',
            name='ordering',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ordering',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
