# Generated by Django 4.2.7 on 2024-04-26 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_app', '0005_alter_groupofproperty_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='business_offer',
            field=models.FileField(blank=True, default='', null=True, upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Коммерческое предложение'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='specification',
            field=models.FileField(blank=True, default='', null=True, upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Спецификация'),
        ),
    ]
