# Generated by Django 4.2.7 on 2024-06-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0004_alter_price_index_together_and_more'),
        ('client_app', '0003_alter_client_created_at_alter_client_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='kind_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='price_app.kindprice', verbose_name='Вид цены'),
        ),
    ]
